/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segundo_parcial;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author cindybohorquezsantana
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About() {
       
       
        initComponents();
         this.setLocationRelativeTo(null);
          ImageIcon imagenicon = new ImageIcon("/Users/cindybohorquezsantana/NetBeansProjects/Segundo_Parcial22/Segundo_Parcial/src/imagenes/z4.gif");
        Icon icon = new ImageIcon(imagenicon.getImage().getScaledInstance(lblAb.getWidth(), lblAb.getHeight(), Image.SCALE_DEFAULT));
        lblAb.setIcon(icon);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblC = new javax.swing.JLabel();
        lblE = new javax.swing.JLabel();
        lblD = new javax.swing.JLabel();
        lblAb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("MENÚ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        lblC.setFont(new java.awt.Font("Lucida Sans", 1, 48)); // NOI18N
        lblC.setForeground(new java.awt.Color(255, 255, 255));
        lblC.setText("Cindy Bohórquez");
        getContentPane().add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        lblE.setFont(new java.awt.Font("Lucida Sans", 1, 48)); // NOI18N
        lblE.setForeground(new java.awt.Color(255, 255, 255));
        lblE.setText("Edwin Ulluguari");
        getContentPane().add(lblE, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        lblD.setFont(new java.awt.Font("Lucida Sans", 1, 48)); // NOI18N
        lblD.setForeground(new java.awt.Color(255, 255, 255));
        lblD.setText("Daniel Saigua ");
        getContentPane().add(lblD, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));
        getContentPane().add(lblAb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       MenuPrincipal m = new MenuPrincipal();
       m.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAb;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblE;
    // End of variables declaration//GEN-END:variables
}
